# Generated by Django 6.0.5 on 2026-05-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('bus', models.ForeignKey(db_column='placa', on_delete=django.db.models.deletion.PROTECT, to='rutas.bus')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='usuarios.cliente')),
                ('horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.PROTECT, to='rutas.horario')),
                ('tarjeta', models.ForeignKey(db_column='id_tarjeta', on_delete=django.db.models.deletion.PROTECT, to='usuarios.tarjeta')),
            ],
            options={
                'db_table': 'tiquetes',
                'constraints': [models.CheckConstraint(condition=models.Q(('monto_pagado__gte', 0)), name='chk_tiquetes_monto_positivo')],
            },
        ),
    ]
