# Generated by Django 6.0.5 on 2026-05-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('pasaporte', models.CharField(max_length=20, unique=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=20, unique=True)),
                ('ccv', models.CharField(max_length=4)),
                ('fecha_vencimiento', models.DateField()),
                ('titular', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
            options={
                'db_table': 'tarjetas',
            },
        ),
    ]
