# Generated by Django 6.0.5 on 2026-05-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='usuarios.cliente'),
        ),
    ]
