# Generated by Django 6.0.5 on 2026-05-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_salida', models.CharField(max_length=50)),
                ('lugar_llegada', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codigo_ruta', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'buses',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacidad__gt', 0)), name='chk_buses_capacidad_positiva')],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField()),
                ('ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
    ]
